# Programming Assignment_8

### Q1. Write a Python Program to Add Two Matrices?

In [1]:
mat1 = [[1,2,4],
        [4,5,6],
        [7,8,9]]

mat2 = [[2,3,4],
        [5,6,7],
        [8,9,1]]

sumMat = [[0,0,0],
          [0,0,0],
          [0,0,0]]

sumMat = [[mat1[i][j] + mat2[i][j] for j in range(len(mat1[0]))] for i in range(len(mat1))]
print("The Sum of two matrix {}  and {}  is \n{} ".format(mat1,mat2,sumMat))

The Sum of two matrix [[1, 2, 4], [4, 5, 6], [7, 8, 9]]  and [[2, 3, 4], [5, 6, 7], [8, 9, 1]]  is 
[[3, 5, 8], [9, 11, 13], [15, 17, 10]] 


### OR

In [3]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.add(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 3  5  8]
 [ 9 11 13]
 [15 17 10]] 


### Q2. Write a Python Program to Multiply Two Matrices?

In [4]:
import numpy as np

mat1 = np.array([[1,2,4],
        [4,5,6],
        [7,8,9]])
mat2 = np.array([[2,3,4],
        [5,6,7],
        [8,9,1]])

sumMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,sumMat))

The product of two matrix 

[[1 2 4]
 [4 5 6]
 [7 8 9]]  and 

[[2 3 4]
 [5 6 7]
 [8 9 1]]  is 

[[ 44  51  22]
 [ 81  96  57]
 [126 150  93]] 


OR

In [7]:
A = [[1,2,3],
    [4,5,6],
    [10,11,12]]

B = [[4,3,7],
    [1,3,21],
    [10,11,21]]

result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

for r in result:
    print(r)

[36, 42, 112, 0]
[81, 93, 259, 0]
[171, 195, 553, 0]


### Q3. Write a Python Program to Transpose a Matrix?

In [6]:
X = [[1,2],
    [3 ,4],
    [5 ,6]]

result = [[0,0,0],
         [0,0,0]]


for i in range(len(X)):
    for j in range(len(X[0])):
        result[j][i] = X[i][j]

for r in result:
    print(r)

[1, 3, 5]
[2, 4, 6]


### Q4. Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
str = input("Enter some string")

words = str.split()  # split the string
words.sort()  # sort the words in alphabetic order
for word in words:
    print(word)# print the words

Enter some stringI am doing ineuron data science course 
I
am
course
data
doing
ineuron
science


### Q5. Write a Python Program to Remove Punctuation From a String?

In [10]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''   # punctuations string

str = input("Enter some string with panctuations  :")

# remove punctuation from the string
no_punct = ""  # take no_punct empty string
for char in str:  # char in str
    if char not in punctuations: # if this char not in punctuations string
        no_punct = no_punct + char  # add this char in no_punct

# display the unpunctuated string
print(no_punct) # print  no_punct

Enter some string with panctuations  :This is going to be very crazy #$#%^$&^%@#^%^
This is going to be very crazy 
